const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("electronAPI", {
  openPurchaseSlipWindow: () => ipcRenderer.invoke("purchase-slip-window:open"),
  openSalesSlipWindow: () => ipcRenderer.invoke("sales-slip-window:open"),
  erp: {
    getInitialData: () => ipcRenderer.invoke("erp:get-initial-data"),
    getAllCurrencies: () => ipcRenderer.invoke("erp:get-all-currencies"),
    getAllExchangeRates: () => ipcRenderer.invoke("erp:get-all-exchange-rates"),
    getAllCurrentAccounts: () => ipcRenderer.invoke("erp:get-all-current-accounts"),
    getAllCurrentAccountMovements: () => ipcRenderer.invoke("erp:get-all-current-account-movements"),
    getAllProductBarcodes: () => ipcRenderer.invoke("erp:get-all-product-barcodes"),
    getAllWarehouses: () => ipcRenderer.invoke("erp:get-all-warehouses"),
    getAllStockBalances: () => ipcRenderer.invoke("erp:get-all-stock-balances"),
    getAllPriceLists: () => ipcRenderer.invoke("erp:get-all-price-lists"),
    getAllPriceListItems: () => ipcRenderer.invoke("erp:get-all-price-list-items"),
    getAllDocumentNumbers: () => ipcRenderer.invoke("erp:get-all-document-numbers"),
    savePurchaseSlip: (payload) => ipcRenderer.invoke("erp:save-purchase-slip", payload),
    saveSalesSlip: (payload) => ipcRenderer.invoke("erp:save-sales-slip", payload),
    saveCollection: (payload) => ipcRenderer.invoke("erp:save-collection", payload),
    savePayment: (payload) => ipcRenderer.invoke("erp:save-payment", payload),
    addProduct: (payload) => ipcRenderer.invoke("erp:add-product", payload),
    updateProduct: (payload) => ipcRenderer.invoke("erp:update-product", payload),
    toggleProductStatus: (id) => ipcRenderer.invoke("erp:toggle-product-status", id),
    addCustomer: (payload) => ipcRenderer.invoke("erp:add-customer", payload),
    updateCustomer: (payload) => ipcRenderer.invoke("erp:update-customer", payload),
    toggleCustomerStatus: (id) => ipcRenderer.invoke("erp:toggle-customer-status", id),
    addSupplier: (payload) => ipcRenderer.invoke("erp:add-supplier", payload),
    updateSupplier: (payload) => ipcRenderer.invoke("erp:update-supplier", payload),
    toggleSupplierStatus: (id) => ipcRenderer.invoke("erp:toggle-supplier-status", id),
  },
});
