export const currentReleaseVersion = "v1.87.0";

export const currentReleaseTitle = "Kapalı Pilot Kullanım Rehberi ve İlk Gün Kontrol Akışı";

export const updatedSectionIds = ["latest-version-history", "system-workflow-model", "dashboard-erp-v1-pilot-summary"];

export const releaseHighlightItems = [
  "Kapalı pilotun ilk günü için Dashboard içinde sade İlk Gün Kullanım Rehberi eklendi.",
  "Pilot dışı bırakılan cari, sipariş, kasa/finans, import/export/sync, Top 100 ve metadata keşfi alanları açık uyarı olarak görünür hale getirildi.",
  "Bu sürüm yeni modül, SQL/Vega bağlantısı, sorgu, metadata otomasyonu, Top 100 aktivasyonu, veri yazma/import/senkron/export veya localStorage eklemez.",
];

export const releaseJumpLinks = [
  { id: "latest-version-history", label: "Son Sürüm Geçmişi'ne git" },
  { id: "dashboard-erp-v1-pilot-summary", label: "ERP v1 Kapalı Pilot Özetine git" },
  { id: "dashboard-readonly-closed-pilot-prep", label: "Read-only Kapalı Pilot Hazırlığı'na git" },
  { id: "vega-stock-movement-field-discovery", label: "Stok Hareket Metadata Keşif Aracı'na git" },
  { id: "vega-top-100-stock-out-preview", label: "Vega Top 100 Stok Çıkışı'na git" },
  { id: "dashboard-top-100-stock-out-preview-summary", label: "Top 100 Stok Çıkışı Dashboard Özetine git" },
  { id: "dashboard-stock-field-label-clarification-plan", label: "Stok Alan Etiketi Planı'na git" },
  { id: "dashboard-stock-preview-user-test-session", label: "Stok Önizleme Kullanıcı Test Oturumu'na git" },
  { id: "dashboard-stock-preview-user-validation-flow", label: "Stok Önizleme Kullanıcı Doğrulama Akışı'na git" },
  { id: "dashboard-stock-smoke-test-result-summary", label: "Stok Smoke Test Sonuç Özeti'ne git" },
  { id: "dashboard-sa-controlled-stock-readonly-mode", label: "sa Kontrollü Stok Read-only Modu'na git" },
  { id: "dashboard-readonly-sql-user-transition-plan", label: "Read-only SQL Kullanıcısı Geçiş Planı'na git" },
  { id: "dashboard-company-readonly-pretest", label: "Şirket Ortamı Ön Test'e git" },
  { id: "dashboard-vega-stock-readonly-precheck", label: "Vega Stok Read-only Ön Kontrol'e git" },
  { id: "dashboard-stock-management-roadmap", label: "Stok Yönetimi Geliştirme Yol Haritası'na git" },
  { id: "dashboard-barcode-handheld-roadmap", label: "Barkod / El Terminali Geliştirme Yol Haritası'na git" },
  { id: "dashboard-erp-module-priority-order", label: "ERP Modül Öncelik Sıralaması'na git" },
  { id: "dashboard-staff-usage-screen-map", label: "Personel Kullanım Ekranları Haritası'na git" },
  { id: "dashboard-data-field-dictionary", label: "Veri Alan Sözlüğü'ne git" },
  { id: "dashboard-risk-warning-center", label: "Risk ve Uyarı Merkezi'ne git" },
  { id: "dashboard-daily-operation-workflow-center", label: "Günlük Operasyon İş Akışı Merkezi'ne git" },
  { id: "dashboard-role-permission-matrix", label: "Rol ve Yetki Matrisi'ne git" },
  { id: "dashboard-erp-main-backbone-module-map", label: "ERP Ana Omurga ve Modül Haritası'na git" },
  { id: "stock-preview-beta-package-status", label: "Stok Önizleme Beta Hazırlığı'na git" },
  { id: "system-workflow-model", label: "Çalışma Modeli'ne git" },
];

export const releaseVisibilityChecklist = [
  "Üstte “Bu Sürümde Yenilenen Alanlar” paneli görünüyor mu?",
  "Hızlı geçiş linkleri ilgili bölüme götürüyor mu?",
  "YENİ etiketi güncel sürüm numarasını gösteriyor mu?",
  "Vurgulanan bölümlerin kenarlığı/arka planı ayırt ediliyor mu?",
];

export const releaseHighlightsByPage = {
  dashboard: {
    releaseHighlightItems,
    releaseJumpLinks: [
      { id: "dashboard-erp-main-backbone-module-map", label: "ERP Ana Omurga ve Modül Haritası'na git" },
      { id: "dashboard-role-permission-matrix", label: "Rol ve Yetki Matrisi'ne git" },
      { id: "dashboard-daily-operation-workflow-center", label: "Günlük Operasyon İş Akışı Merkezi'ne git" },
      { id: "dashboard-staff-usage-screen-map", label: "Personel Kullanım Ekranları Haritası'na git" },
      { id: "dashboard-erp-module-priority-order", label: "ERP Modül Öncelik Sıralaması'na git" },
      { id: "dashboard-stock-management-roadmap", label: "Stok Yönetimi Geliştirme Yol Haritası'na git" },
      { id: "dashboard-erp-v1-pilot-summary", label: "ERP v1 Kapalı Pilot Özetine git" },
      { id: "dashboard-readonly-closed-pilot-prep", label: "Read-only Kapalı Pilot Hazırlığı'na git" },
      { id: "dashboard-top-100-stock-out-preview-summary", label: "Top 100 Stok Çıkışı Dashboard Özetine git" },
      { id: "dashboard-stock-preview-user-validation-flow", label: "Stok Önizleme Kullanıcı Doğrulama Akışı'na git" },
      { id: "dashboard-stock-preview-user-test-session", label: "Stok Önizleme Kullanıcı Test Oturumu'na git" },
      { id: "dashboard-company-readonly-pretest", label: "Şirket Ortamı Ön Test'e git" },
      { id: "dashboard-stock-smoke-test-result-summary", label: "Stok Smoke Test Sonuç Özeti'ne git" },
      { id: "dashboard-sa-controlled-stock-readonly-mode", label: "sa Kontrollü Stok Read-only Modu'na git" },
      { id: "dashboard-readonly-sql-user-transition-plan", label: "Read-only SQL Kullanıcısı Geçiş Planı'na git" },
      { id: "dashboard-barcode-handheld-roadmap", label: "Barkod / El Terminali Geliştirme Yol Haritası'na git" },
      { id: "dashboard-risk-warning-center", label: "Risk ve Uyarı Merkezi'ne git" },
      { id: "dashboard-data-field-dictionary", label: "Veri Alan Sözlüğü'ne git" },
      { id: "dashboard-stock-field-label-clarification-plan", label: "Stok Alan Etiketi Planı'na git" },
      { id: "dashboard-owner-view", label: "Patron Bakışı'na git" },
      { id: "dashboard-vega-readonly-operation-center", label: "Vega Read-only Operasyon Merkezi'ne git" },
      { id: "dashboard-vega-readonly-module-matrix", label: "Vega Read-only Modül Durum Matrisi'ne git" },
      { id: "dashboard-live-decision-panel", label: "Canlıya Geçiş Karar Paneli'ne git" },
      { id: "dashboard-live-missing-list", label: "Canlıya Geçiş Eksik Listesi'ne git" },
      { id: "dashboard-readonly-test-report-prep", label: "Read-only Test Raporu Hazırlığı'na git" },
      { id: "dashboard-owner-approval-package-prep", label: "Patron Onay Paketi Hazırlığı'na git" },
      { id: "dashboard-management-presentation-summary", label: "Yönetici Sunum Özeti'ne git" },
      { id: "dashboard-vega-stock-readonly-hardening", label: "Vega Stok Read-only Sağlamlaştırma'ya git" },
      { id: "dashboard-vega-stock-readonly-precheck", label: "Vega Stok Read-only Ön Kontrol'e git" },
      { id: "dashboard-vega-stock-readonly-local-test-prep", label: "Vega Stok Read-only Local Test Hazırlığı'na git" },
      { id: "dashboard-finance-preview-prep-gate", label: "Kasa/Finans Özeti Hazırlık Kapısı'na git" },
      { id: "dashboard-current-preview-prep-gate", label: "Cari Önizleme Hazırlık Kapısı'na git" },
      { id: "dashboard-order-preview-prep-gate", label: "Sipariş Önizleme Hazırlık Kapısı'na git" },
      { id: "dashboard-stock-preview-beta-package", label: "Stok Önizleme Beta Hazırlığı'na git" },
      { id: "dashboard-vega-stock-screen-simplification", label: "Vega Stok Sadeleştirme'ye git" },
      { id: "dashboard-stock-preview-user-test", label: "Stok Önizleme Kullanıcı Testi'ne git" },
      { id: "dashboard-stock-preview-panel-simplification", label: "Stok Önizleme Panel Sadeleştirme'ye git" },
      { id: "dashboard-stock-column-visibility", label: "Kolon Görünürlüğü Kontrolü'ne git" },
      { id: "dashboard-stock-field-labeling-prep", label: "Stok Alan Etiketleme Hazırlığı'na git" },
      { id: "dashboard-stock-manual-validation-checklist", label: "Manuel Doğrulama Checklist’ine git" },
      { id: "dashboard-stock-field-validation-prep", label: "Stok Alan Doğrulama'ya git" },
      { id: "dashboard-stock-preview-usability", label: "Stok Önizleme Kullanım İyileştirme'ye git" },
      { id: "dashboard-stock-preview-security-confirmation", label: "Stok Önizleme Güvenlik Teyidi'ne git" },
      { id: "dashboard-readonly-stock-preview", label: "Read-only Stok Önizleme'ye git" },
      { id: "dashboard-successful-stock-read-proof", label: "Başarılı Stok Okuma Kanıtı'na git" },
      { id: "dashboard-closed-beta-preparation", label: "Kapalı Beta Hazırlığı'na git" },
      { id: "dashboard-desktop-preparation-center", label: "Desktop Hazırlık Merkezi'ne git" },
      { id: "dashboard-passive-vega-connection-status", label: "Vega Bağlantı Durumu'na git" },
      { id: "dashboard-vega-stock-field-map", label: "Stok Alan Haritası'na git" },
      { id: "dashboard-readonly-stock-smoke-summary", label: "İlk Stok Okuma Denemesi'ne git" },
      { id: "dashboard-readonly-environment-prep-summary", label: "Read-only Ortam Hazırlığı'na git" },
      { id: "dashboard-readonly-fail-closed-summary", label: "Read-only Fail-closed Özeti'ne git" },
      { id: "dashboard-readonly-final-security-scan-summary", label: "Read-only Son Güvenlik Taraması'na git" },
      { id: "dashboard-readonly-operator-checklist-summary", label: "Read-only Operatör Checklist Özeti'ne git" },
      { id: "dashboard-readonly-connection-skeleton-summary", label: "Read-only Altyapı Özeti'ne git" },
      { id: "dashboard-readonly-final-security-summary", label: "Read-only Final Güvenlik Özeti'ne git" },
      { id: "dashboard-readonly-final-decision-summary", label: "Read-only Son Karar Özeti'ne git" },
      { id: "dashboard-readonly-first-trial-summary", label: "İlk Deneme Planı Özeti'ne git" },
      { id: "dashboard-vega-technical-gate-summary", label: "Vega Teknik Ön Kapı Özeti'ne git" },
      { id: "dashboard-module-maturity-score-center", label: "Modül Olgunluk Skor Merkezi'ne git" },
      { id: "dashboard-prelive-operation-test-center", label: "Canlı Öncesi Test Merkezi'ne git" },
      { id: "dashboard-reporting-decision-center", label: "Raporlama ve Yönetici Karar Merkezi'ne git" },
      { id: "dashboard-commerce-profitability-center", label: "Alış Satış ve Kârlılık Merkezi'ne git" },
      { id: "dashboard-daily-operation", label: "Bugünkü Operasyon Özeti'ne git" },
      { id: "dashboard-currency-summary", label: "Dövizli Ticaret Özeti'ne git" },
      { id: "dashboard-commerce-insights", label: "Ticari Grafik Özeti'ne git" },
    ],
    updatedSectionIds: ["dashboard-erp-v1-pilot-summary", "dashboard-readonly-closed-pilot-prep", "dashboard-stock-management-roadmap"],
  },
  reports: {
    releaseHighlightItems,
    releaseJumpLinks: [
      { id: "reports-module-maturity-center", label: "Modül Olgunluk Skor Merkezi'ne git" },
      { id: "reports-module-maturity-table", label: "Modül Bazlı Olgunluk Tablosu'na git" },
      { id: "reports-go-live-barometer", label: "Canlıya Geçiş Barometresi'ne git" },
      { id: "reports-closed-areas", label: "Kapalı ve Yasaklı Alanlar'a git" },
      { id: "reports-prelive-test-center", label: "Canlı Öncesi Test Merkezi'ne git" },
    ],
    updatedSectionIds: ["reports-module-maturity-center", "reports-module-maturity-table", "reports-go-live-barometer", "reports-closed-areas"],
  },
  customers: {
    releaseHighlightItems,
    releaseJumpLinks: [
      { id: "current-account-risk-center", label: "Cari Risk Merkezi'ne git" },
      { id: "current-account-risk-classes", label: "Risk Sınıfları'na git" },
      { id: "receivable-priority-matrix", label: "Alacak Öncelik Matrisi'ne git" },
      { id: "collection-preparation-guide", label: "Tahsilat Hazırlık Rehberi'ne git" },
    ],
    updatedSectionIds: ["current-account-risk-center", "current-account-risk-classes", "receivable-priority-matrix", "collection-preparation-guide"],
  },
  vegaStockTrial: {
    releaseHighlightItems,
    releaseJumpLinks: [
      { id: "vega-stock-trial-panel", label: "Vega Stok Deneme alanına git" },
      { id: "vega-stock-movement-field-discovery", label: "Stok Hareket Metadata Keşif Aracı'na git" },
      { id: "vega-top-100-stock-out-preview", label: "Top 100 Stok Çıkışı alanına git" },
      { id: "vega-stock-user-validation-panel", label: "Kullanıcı Doğrulama Paneli'ne git" },
    ],
    updatedSectionIds: ["vega-stock-movement-field-discovery", "vega-top-100-stock-out-preview"],
  },
  vegaImportPreview: {
    releaseHighlightItems,
    releaseJumpLinks: [
      { id: "vega-readonly-stock-smoke-test", label: "İlk Stok Okuma Denemesi'ne git" },
      { id: "vega-readonly-stock-preview", label: "Read-only Stok Önizleme'ye git" },
      { id: "vega-stock-preview-beta-note", label: "Kapalı Beta Test Notu'na git" },
      { id: "vega-stock-last-read-summary", label: "Son Okuma Özeti'ne git" },
      { id: "vega-advanced-field-validation", label: "Gelişmiş Alan Doğrulama'ya git" },
      { id: "vega-stock-user-test-notes", label: "Kullanıcı Test Notu'na git" },
      { id: "vega-stock-preview-support-panels", label: "Önizleme Destek Panelleri'ne git" },
      { id: "vega-stock-column-visibility", label: "Kolon Görünürlüğü'ne git" },
      { id: "vega-stock-suggested-field-labels", label: "Önerilen Alan Etiketleri'ne git" },
      { id: "vega-stock-field-validation-notes", label: "Alan Doğrulama Notları'na git" },
      { id: "vega-stock-manual-validation-checklist", label: "Manuel Doğrulama Checklist’ine git" },
      { id: "vega-readonly-environment-prep-center", label: "Ortam Bilgisi Hazırlığı'na git" },
      { id: "vega-environment-prep-table", label: "Ortam Bilgisi Tablosu'na git" },
      { id: "vega-role-environment-prep", label: "Rol Bazlı Ortam Hazırlığı'na git" },
      { id: "vega-test-environment-decision-guide", label: "Test Ortamı Karar Rehberi'ne git" },
      { id: "vega-readonly-fail-closed-shell", label: "Fail-closed Hazırlık Kabuğu'na git" },
      { id: "vega-fail-closed-rules", label: "Fail-closed Kuralları'na git" },
      { id: "vega-blocked-behaviors", label: "Bloke Edilen Davranışlar'a git" },
      { id: "vega-first-real-connection-boundary", label: "Teknik Sınır'a git" },
      { id: "vega-readonly-final-security-scan", label: "Son Güvenlik Taraması'na git" },
      { id: "vega-final-security-cleanup-list", label: "Son Güvenlik Kontrol Listesi'ne git" },
      { id: "vega-readonly-operator-checklist-center", label: "Operatör Checklist Merkezi'ne git" },
      { id: "vega-operator-final-checklist", label: "Operatör Son Kontrol Listesi'ne git" },
      { id: "vega-role-based-control-panel", label: "Rol Bazlı Kontrol Paneli'ne git" },
      { id: "vega-next-small-phase-prep", label: "Sonraki Küçük Faz Hazırlığı'na git" },
      { id: "vega-readonly-connection-skeleton", label: "Pasif Teknik İskelet'e git" },
      { id: "vega-technical-infrastructure-locks", label: "Teknik Altyapı Kilitleri'ne git" },
      { id: "vega-first-connection-scope-limit", label: "İlk Bağlantı Kapsam Sınırı'na git" },
      { id: "vega-readonly-final-security-closure", label: "Final Güvenlik Kapanışı'na git" },
      { id: "vega-closed-security-locks", label: "Kapatılan Kilitler'e git" },
      { id: "vega-not-to-do-list", label: "Yapılmayacak İşlemler'e git" },
      { id: "vega-next-small-phase-boundary", label: "Sonraki Küçük Faz Sınırı'na git" },
      { id: "vega-readonly-final-decision-center", label: "Son Karar Merkezi'ne git" },
      { id: "vega-start-stop-decision-logic", label: "Başla / Başlama Mantığı'na git" },
      { id: "vega-final-decision-matrix", label: "Son Karar Matrisi'ne git" },
      { id: "vega-final-security-lock", label: "Son Güvenlik Kilidi'ne git" },
      { id: "vega-readonly-first-trial-plan", label: "İlk Deneme Planı'na git" },
      { id: "vega-first-trial-timeline", label: "Zaman Çizelgesi'ne git" },
      { id: "vega-rollback-procedure", label: "Rollback Prosedürü'ne git" },
      { id: "vega-post-test-template", label: "Değerlendirme Şablonu'na git" },
      { id: "vega-readonly-technical-gate-center", label: "Teknik Ön Kapı Merkezi'ne git" },
      { id: "vega-readonly-required-conditions", label: "Zorunlu Şartlar'a git" },
      { id: "vega-technical-lock-matrix", label: "Teknik Kilit Matrisi'ne git" },
      { id: "vega-first-readonly-procedure", label: "İlk Deneme Prosedürü'ne git" },
      { id: "vega-import-preview-panel", label: "Vega Import Önizleme alanına git" },
      { id: "vega-import-quality-note", label: "Kalite Kontrol Notu'na git" },
      { id: "vega-readonly-roadmap", label: "Read-only Yol Haritası'na git" },
    ],
    updatedSectionIds: ["vega-stock-preview-beta-note", "vega-readonly-stock-preview"],
  },

  warehouseTerminal: {
    releaseHighlightItems,
    releaseJumpLinks: [
      { id: "warehouse-barcode-operation-center", label: "Operasyon Merkezi'ne git" },
      { id: "warehouse-stock-barcode-quality-center", label: "Kalite Kontrol Merkezi'ne git" },
      { id: "warehouse-risk-priority-matrix", label: "Risk Öncelik Matrisi'ne git" },
      { id: "warehouse-barcode-risk-panel", label: "Barkod Riskleri'ne git" },
    ],
    updatedSectionIds: ["warehouse-barcode-operation-center", "warehouse-stock-barcode-quality-center", "warehouse-risk-priority-matrix", "warehouse-barcode-risk-panel"],
  },
  settings: {
    releaseHighlightItems,
    releaseJumpLinks,
    testChecklist: releaseVisibilityChecklist,
    updatedSectionIds,
  },
};
